name    'puppet-share'
version '1.0.0'
source 'http://github.com/kcrawford/puppet-share'
author 'Kyle Crawford'
license 'Apache License, Version 2.0'
summary 'A puppet module for creating and managing file shares'
description 'Create and manage file shares'
project_page 'http://github.com/kcrawford/puppet-share'
